// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Svg          = require("../src/svg.bs.js");
var Mocha        = require("./mocha.bs.js");
var Option       = require("bs-batteries/lib/js/src/option.js");
var ElementRe    = require("bs-webapi/lib/js/src/dom/nodes/ElementRe.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var svgOpt = document.getElementById("svg");

var svgroot = Option.get(svgOpt === null ? /* None */0 : [svgOpt]);

ElementRe.insertAdjacentHTML(/* AfterBegin */1, "<circle id=\"c\" cx=\"20\" cy=\"20\" r=\"10\" style=\"fill: rgb(60, 120, 5); fill-opacity: 0.5\"></circle>", svgroot);

var circle_001 = /* elem */Option.get(Js_primitive.null_to_opt(document.getElementById("c")));

var circle = /* record */[
  /* rootElem */svgroot,
  circle_001
];

it("coordinates", (function () {
        var leftTop = Svg.getLeftTop(circle);
        var center = Svg.getCenter(circle);
        var rightBottom = Svg.getRightBottom(circle);
        Mocha.floatEq("leftTop", leftTop[/* x */0], 10.0);
        Mocha.floatEq("center", center[/* x */0], 20.0);
        return Mocha.floatEq("rightBottom", rightBottom[/* x */0], 30.0);
      }));

it("color", (function () {
        var fillColor = Svg.getFillColor(circle);
        if (typeof fillColor === "number") {
          return Mocha.fail("not Rgba");
        } else if (fillColor.tag) {
          return Mocha.fail("not Rgba");
        } else {
          var rgba = fillColor[0];
          Mocha.intEq("color r", rgba[/* r */0], 60);
          Mocha.intEq("color g", rgba[/* g */1], 120);
          Mocha.intEq("color b", rgba[/* b */2], 5);
          return Mocha.floatEq("color a", rgba[/* a */3], 0.5);
        }
      }));

/* svgOpt Not a pure module */
