// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Svg          = require("../src/svg.bs.js");
var Block        = require("bs-platform/lib/js/block.js");
var Mocha        = require("./mocha.bs.js");
var Option       = require("bs-batteries/lib/js/src/option.js");
var ElementRe    = require("bs-webapi/lib/js/src/dom/nodes/ElementRe.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var svgOpt = document.getElementById("svg");

var svgroot = Option.get(svgOpt === null ? /* None */0 : [svgOpt]);

ElementRe.insertAdjacentHTML(/* AfterBegin */1, "<circle id=\"c\"></circle>", svgroot);

function circle() {
  return Option.get(Js_primitive.null_to_opt(document.getElementById("c")));
}

beforeEach((function () {
        var c = Option.get(Js_primitive.null_to_opt(document.getElementById("c")));
        c.setAttribute("cx", "20");
        c.setAttribute("cy", "20");
        c.setAttribute("r", "10");
        c.setAttribute("style", "fill: rgb(60, 120, 5); fill-opacity: 0.5");
        return /* () */0;
      }));

it("coordinates", (function () {
        Mocha.floatEq("leftTop", Svg.getLeftTop(svgroot, circle(/* () */0))[/* x */0], 10.0);
        Mocha.floatEq("center", Svg.getCenter(svgroot, circle(/* () */0))[/* x */0], 20.0);
        Mocha.floatEq("rightBottom", Svg.getRightBottom(svgroot, circle(/* () */0))[/* x */0], 30.0);
        Svg.setLeftTop(/* float array */[
              0.0,
              10.0
            ], svgroot, circle(/* () */0));
        Mocha.floatEq("leftTop'", Svg.getLeftTop(svgroot, circle(/* () */0))[/* x */0], 0.0);
        Mocha.floatEq("center'", Svg.getCenter(svgroot, circle(/* () */0))[/* x */0], 10.0);
        return Mocha.floatEq("rightBottom'", Svg.getRightBottom(svgroot, circle(/* () */0))[/* x */0], 20.0);
      }));

it("color", (function () {
        var match = Svg.getFillColor(circle(/* () */0));
        if (typeof match === "number") {
          Mocha.fail("not Rgba");
        } else if (match.tag) {
          Mocha.fail("not Rgba");
        } else {
          var rgba = match[0];
          Mocha.intEq("color r", rgba[/* r */0], 60);
          Mocha.intEq("color g", rgba[/* g */1], 120);
          Mocha.intEq("color b", rgba[/* b */2], 5);
          Mocha.floatEq("color a", rgba[/* a */3], 0.5);
        }
        Svg.setFillColor(/* Rgba */Block.__(0, [/* record */[
                  /* r */10,
                  /* g */20,
                  /* b */30,
                  /* a */0.6
                ]]), circle(/* () */0));
        var match$1 = Svg.getFillColor(circle(/* () */0));
        if (typeof match$1 === "number") {
          return Mocha.fail("not Rgba");
        } else if (match$1.tag) {
          return Mocha.fail("not Rgba");
        } else {
          var rgba$1 = match$1[0];
          Mocha.intEq("color r", rgba$1[/* r */0], 10);
          Mocha.intEq("color g", rgba$1[/* g */1], 20);
          Mocha.intEq("color b", rgba$1[/* b */2], 30);
          return Mocha.floatEq("color a", rgba$1[/* a */3], 0.6);
        }
      }));

/* svgOpt Not a pure module */
