// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry                   = require("bs-platform/lib/js/curry.js");
var Pervasives              = require("bs-platform/lib/js/pervasives.js");
var Natives$BsSvgAttachment = require("./natives.bs.js");

function getBBox(elem) {
  var rect = Curry._1(Natives$BsSvgAttachment.getBBox, elem);
  console.log(rect);
  return /* record */[
          /* leftTop : float array */[
            rect.x,
            rect.y
          ],
          /* rightBottom : float array */[
            rect.x + rect.width,
            rect.y + rect.height
          ]
        ];
}

function merge(a, b) {
  var left = Pervasives.min(a[/* leftTop */0][/* x */0], b[/* leftTop */0][/* x */0]);
  var top = Pervasives.min(a[/* leftTop */0][/* y */1], b[/* leftTop */0][/* y */1]);
  var right = Pervasives.max(a[/* rightBottom */1][/* x */0], b[/* rightBottom */1][/* x */0]);
  var bottom = Pervasives.max(a[/* rightBottom */1][/* y */1], b[/* rightBottom */1][/* y */1]);
  return /* record */[
          /* leftTop : float array */[
            left,
            top
          ],
          /* rightBottom : float array */[
            right,
            bottom
          ]
        ];
}

exports.getBBox = getBBox;
exports.merge   = merge;
/* Natives-BsSvgAttachment Not a pure module */
