// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry      = require("bs-platform/lib/js/curry.js");
var Natives    = require("./natives.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function getRBox(elem) {
  var rect = Curry._1(Natives.getBoundingClientRect, elem);
  return /* record */[
          /* leftTop : float array */[
            rect.left,
            rect.top
          ],
          /* rightBottom : float array */[
            rect.right,
            rect.bottom
          ]
        ];
}

function merge(a, b) {
  var left = Pervasives.min(a[/* leftTop */0][/* x */0], b[/* leftTop */0][/* x */0]);
  var top = Pervasives.min(a[/* leftTop */0][/* y */1], b[/* leftTop */0][/* y */1]);
  var right = Pervasives.max(a[/* rightBottom */1][/* x */0], b[/* rightBottom */1][/* x */0]);
  var bottom = Pervasives.max(a[/* rightBottom */1][/* y */1], b[/* rightBottom */1][/* y */1]);
  return /* record */[
          /* leftTop : float array */[
            left,
            top
          ],
          /* rightBottom : float array */[
            right,
            bottom
          ]
        ];
}

exports.getRBox = getRBox;
exports.merge   = merge;
/* Natives Not a pure module */
