// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var getBoundingClientRect = ( x => x.getBoundingClientRect() );

exports.getBoundingClientRect = getBoundingClientRect;
/* getBoundingClientRect Not a pure module */
