// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function $plus$caret(a, b) {
  return /* float array */[
          a[/* x */0] + b[/* x */0],
          a[/* y */1] + b[/* y */1]
        ];
}

function $neg$caret(a, b) {
  return /* float array */[
          a[/* x */0] - b[/* x */0],
          a[/* y */1] - b[/* y */1]
        ];
}

function $star$caret(a, b) {
  return /* float array */[
          a[/* x */0] * b[/* x */0],
          a[/* y */1] * b[/* y */1]
        ];
}

function $slash$caret(a, b) {
  return /* float array */[
          a[/* x */0] / b[/* x */0],
          a[/* y */1] / b[/* y */1]
        ];
}

exports.$plus$caret  = $plus$caret;
exports.$neg$caret   = $neg$caret;
exports.$star$caret  = $star$caret;
exports.$slash$caret = $slash$caret;
/* No side effect */
