// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry        = require("bs-platform/lib/js/curry.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function getAttr(t, name) {
  return Js_primitive.null_undefined_to_opt(Curry._1(t[/* elem */1][/* getAttribute */0], name));
}

function setAttr(t, name, value) {
  return Curry._2(t[/* elem */1][/* setAttribute */1], name, value);
}

function deleteAttr(t, name) {
  return Curry._2(t[/* elem */1][/* setAttribute */1], name, ( null ));
}

function getBBox(t) {
  return Curry._1(t[/* elem */1][/* getBoundingClientRect */2], /* () */0);
}

exports.getAttr    = getAttr;
exports.setAttr    = setAttr;
exports.deleteAttr = deleteAttr;
exports.getBBox    = getBBox;
/* No side effect */
