// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function add(a, b) {
  return /* float array */[
          a[/* x */0] + b[/* x */0],
          a[/* y */1] + b[/* y */1]
        ];
}

function sub(a, b) {
  return /* float array */[
          a[/* x */0] - b[/* x */0],
          a[/* y */1] - b[/* y */1]
        ];
}

exports.add = add;
exports.sub = sub;
/* No side effect */
